import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AOSInit from "@/utils/aos";
import ScrollToTop from "@/utils/scrollToTop";
import ToastProvider from "@/components/modules/toast/ToastProvider";
import { ContextProvider } from "@/context/ContextApi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "صفحه اصلی | set-coffee",
  description: "Generated by create next app",
  icons: {
    icon: "https://set-coffee.com/wp-content/uploads/2022/03/cropped-512x5122-1-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ContextProvider>
          <AOSInit />
          <ToastProvider />
          {children}
          <ScrollToTop />
        </ContextProvider>
      </body>
    </html>
  );
}
